# Anaconda environmnet for datasciY repo on Github.com  
name: datasciy-env
# "conda env export > environment.yml" to save existing environment to file 
dependencies:
- python=3.7
- numpy
- matplotlib
- seaborn
- jupyter
- pandas
- pandas-datareader
- quandl
- beautifulsoup4
- scikit-learn
