# Anaconda environmnet for Jupyter notebooks hosted on mybinder.org
name: notebooks-env
# "conda env export > environment.yml" to save existing environment to file 
dependencies:
- python=3.7
- numpy
- matplotlib
- seaborn
- pandas
- jupyter
- pandas-datareader
- quandl
- beautifulsoup4
- scikit-learn
