# Anaconda environmnet for datasciy.com, Jupyter notebooks hosted on mybinder.org
name: datasciy-binder
# "conda env export > environment.yml" to save existing environment to file 
dependencies:
- python=3.7
- numpy
- matplotlib
- seaborn
- jupyter
- pandas
- pandas-datareader
- quandl
- beautifulsoup4
- scikit-learn
